apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName}}
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.containers.dgraph_zero.grpcPort }}
      targetPort: {{ .Values.containers.dgraph_zero.grpcPort }}
      name: grpc-zero
    - port: {{ .Values.containers.dgraph_zero.httpPort }}
      nodePort: 30080
      targetPort: {{ .Values.containers.dgraph_zero.httpPort }}
      name: http-zero
    - port: {{ .Values.containers.dgraph_alpha.httpPort }}
      targetPort: {{ .Values.containers.dgraph_alpha.httpPort }}
      name: http-alpha
    - port: {{ .Values.containers.dgraph_alpha.grpcPort }}
      targetPort: {{ .Values.containers.dgraph_alpha.grpcPort }}
      name: grpc-alpha
  selector:
    app: {{ .Values.selectorLabel }}


